name: Flarie App CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-image-bangla-style:
    name: Build and Push App Image to Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Registry
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "junkcodes" --password-stdin
    - name: Build Image
      run: docker build -t junkcodes/flarie:bs -f dockerfile/Dockerfile .
    - name: Push Image
      run: docker push junkcodes/flarie:bs

